dtb-$(CONFIG_ARCH_MSM8998) += \
	msm8998-v2.1-htc_ocm-xa.dtb \
	msm8998-v2.1-htc_ocm-xb.dtb \
	msm8998-v2.1-htc_ocm-xc.dtb \
	msm8998-v2.1-htc_ocm-pvt.dtb \

always         := $(dtb-y)
subdir-y       := $(dts-dirs)
clean-files    := *.dtb
